### ISSUE TITLE
Customer Management

### ISSUE THREAD

**Issue by NandiyaLive** [RestroHQ/backend#10]
### Description
Implement customer profile management and loyalty system.

### Tasks
- [x] Create Prisma schema for:
  - Customer profiles
- [x] Implement API endpoints for:
  - Customer CRUD
  - Profile management
  - Order history
- [ ] Add customer analytics?

**Comment by NandiyaLive** [comment]
Okay. Create a feature branch from the development branch.
